copyright:
  year: 2026
  author: "C. Waterton"
  rights: "Tous droits réservés"

publisher:
  name: "Éditions Darkwaters"
  address: "6 Rue des Écoles, 63720 Chavaroux, France"

printing:
  country: "France"

legal_deposit: "mars 2026"
