"""create ebooks table

Revision ID: 097b735e8fb8
Revises: e064f772d88b
Create Date: 2025-09-10 17:41:33.654430

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "097b735e8fb8"
down_revision: str | None = "e064f772d88b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ebooks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("status", sa.Enum("PENDING", "VALIDATED", name="ebookstatus"), nullable=True),
        sa.Column("preview_url", sa.String(), nullable=True),
        sa.Column("drive_id", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ebooks_id"), "ebooks", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ebooks_id"), table_name="ebooks")
    op.drop_table("ebooks")
    # ### end Alembic commands ###
