"""Add token tracking columns to ebooks

Revision ID: 21c0fe290b3a
Revises: 6fcc948b009e
Create Date: 2025-10-02 16:33:25.257307

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21c0fe290b3a"
down_revision: str | None = "6fcc948b009e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ebooks", sa.Column("prompt_tokens", sa.Integer(), nullable=True))
    op.add_column("ebooks", sa.Column("completion_tokens", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ebooks", "completion_tokens")
    op.drop_column("ebooks", "prompt_tokens")
    # ### end Alembic commands ###
