"""Add ebook_bytes column for DRAFT storage

Revision ID: 41b5b1429baa
Revises: 920c999b4bb1
Create Date: 2025-10-01 14:01:02.679354

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41b5b1429baa"
down_revision: str | None = "920c999b4bb1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ebooks", sa.Column("ebook_bytes", sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ebooks", "ebook_bytes")
    # ### end Alembic commands ###
