"""Add provider, model and duration to ebook generation tracking

Revision ID: 4d38adfff641
Revises: 21c0fe290b3a
Create Date: 2025-10-02 19:01:38.200983

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d38adfff641"
down_revision: str | None = "21c0fe290b3a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ebooks", sa.Column("generation_provider", sa.String(length=50), nullable=True))
    op.add_column("ebooks", sa.Column("generation_model", sa.String(length=100), nullable=True))
    op.add_column(
        "ebooks",
        sa.Column("generation_duration_seconds", sa.NUMERIC(precision=10, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ebooks", "generation_duration_seconds")
    op.drop_column("ebooks", "generation_model")
    op.drop_column("ebooks", "generation_provider")
    # ### end Alembic commands ###
