"""Add generation_cost to ebooks table

Revision ID: 6fcc948b009e
Revises: 3ce9199f7afa
Create Date: 2025-10-02 15:50:36.245015

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6fcc948b009e"
down_revision: str | None = "3ce9199f7afa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ebooks", sa.Column("generation_cost", sa.NUMERIC(precision=12, scale=4), nullable=True)
    )
    op.alter_column(
        "ebooks",
        "status",
        existing_type=postgresql.ENUM("DRAFT", "APPROVED", "REJECTED", name="ebookstatus"),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.create_index(op.f("ix_ebooks_generation_cost"), "ebooks", ["generation_cost"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ebooks_generation_cost"), table_name="ebooks")
    op.alter_column(
        "ebooks",
        "status",
        existing_type=sa.String(length=20),
        type_=postgresql.ENUM("DRAFT", "APPROVED", "REJECTED", name="ebookstatus"),
        existing_nullable=False,
    )
    op.drop_column("ebooks", "generation_cost")
    # ### end Alembic commands ###
