"""Add structure_json field to ebooks table

Revision ID: 920c999b4bb1
Revises: d5af74646a86
Create Date: 2025-09-30 11:08:03.464233

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "920c999b4bb1"
down_revision: str | None = "d5af74646a86"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ebooks", sa.Column("structure_json", sa.JSON(), nullable=True))
    op.alter_column(
        "ebooks",
        "status",
        existing_type=postgresql.ENUM(
            "DRAFT", "PENDING", "APPROVED", "REJECTED", name="ebookstatus"
        ),
        type_=sa.String(length=20),
        nullable=False,
    )
    op.alter_column(
        "ebooks",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
    )
    op.drop_index("ix_ebooks_id", table_name="ebooks")
    op.drop_column("users", "updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
    )
    op.create_index("ix_ebooks_id", "ebooks", ["id"], unique=False)
    op.alter_column(
        "ebooks",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "ebooks",
        "status",
        existing_type=sa.String(length=20),
        type_=postgresql.ENUM("DRAFT", "PENDING", "APPROVED", "REJECTED", name="ebookstatus"),
        nullable=True,
    )
    op.drop_column("ebooks", "structure_json")
    # ### end Alembic commands ###
