"""Add page_count column for KDP export

Revision ID: a4fa571b69fb
Revises: 41b5b1429baa
Create Date: 2025-10-01 14:03:59.049821

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4fa571b69fb"
down_revision: str | None = "41b5b1429baa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ebooks", sa.Column("page_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ebooks", "page_count")
    # ### end Alembic commands ###
