"""Add theme metadata fields to ebooks table

Revision ID: d5af74646a86
Revises: ac1b2ce11e70
Create Date: 2025-09-29 17:30:42.412239

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5af74646a86"
down_revision: str | None = "ac1b2ce11e70"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add theme metadata fields for theme-based ebook generation
    op.add_column("ebooks", sa.Column("theme_id", sa.String(length=50), nullable=True))
    op.add_column("ebooks", sa.Column("theme_version", sa.String(length=20), nullable=True))
    op.add_column("ebooks", sa.Column("audience", sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove theme metadata fields
    op.drop_column("ebooks", "audience")
    op.drop_column("ebooks", "theme_version")
    op.drop_column("ebooks", "theme_id")
    # ### end Alembic commands ###
