"""Service for compositing title and footer images onto a generated cover."""

from __future__ import annotations

import io
import logging
from pathlib import Path
from typing import TYPE_CHECKING

from PIL import Image

if TYPE_CHECKING:
    from backoffice.features.ebook.shared.domain.entities.theme_profile import ThemeProfile

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Overlay placement constants (KDP print-safe)
# ---------------------------------------------------------------------------
#
# Amazon KDP trims covers after printing. Two zones matter:
#
#   1. Bleed (0.125" = 38px @300DPI) — will be CUT OFF, never visible.
#   2. Safe zone (0.25" = 75px @300DPI) — may shift slightly during trim.
#
# Minimum safe distance from image edge = bleed + safe zone = 0.375" ≈ 113px.
# Minimum *text* distance from trim line = 0.125" (KDP spec) → 76px from edge.
#
# HOW TO ADJUST SPACING:
#   - To move the TITLE up/down    → change PADDING_PX  (lower = closer to top)
#   - To move the FOOTER up/down   → change FOOTER_BOTTOM_PADDING_PX (lower = closer to bottom)
#   - To limit overlay HEIGHT      → change TITLE/FOOTER_MAX_HEIGHT_RATIO
#   - Hard minimum for any value   → 76px (below that, content enters the bleed zone)
#
# After changing, run:
#   python scripts/verify_cover_overlay.py --theme dinosaurs
# to visually confirm the placement.
# ---------------------------------------------------------------------------

KDP_SAFE_ZONE_INCHES = 0.25
KDP_BLEED_INCHES = 0.125
COVER_DPI = 300

PADDING_PX = 90  # title distance from top edge (76px minimum)
FOOTER_BOTTOM_PADDING_PX = 76  # footer distance from bottom edge (76px minimum)

TITLE_MAX_HEIGHT_RATIO = 0.25  # title occupies at most 25% of cover height
FOOTER_MAX_HEIGHT_RATIO = 0.20  # footer occupies at most 20% of cover height


# Allowed base directories for overlay images (relative to project root)
_ALLOWED_OVERLAY_PREFIXES = ("config/branding/",)


class CoverCompositor:
    """Composites title and footer PNG overlays onto a generated cover image."""

    @staticmethod
    def _validate_overlay_path(image_path: str) -> bool:
        """Validate that an overlay path is safe (no path traversal).

        Only paths under allowed prefixes are accepted. This prevents
        reading arbitrary files if theme YAMLs become user-editable.

        Args:
            image_path: Path string to validate

        Returns:
            True if path is safe, False otherwise
        """
        if not image_path:
            return False

        # Reject path traversal attempts
        if ".." in str(Path(image_path)):
            logger.warning(f"Rejected overlay path (traversal attempt): {image_path}")
            return False

        # Must start with an allowed prefix
        for prefix in _ALLOWED_OVERLAY_PREFIXES:
            if image_path.startswith(prefix):
                return True

        logger.warning(f"Rejected overlay path (not in allowed directory): {image_path}")
        return False

    def apply_cover_overlays(
        self,
        cover_data: bytes,
        theme_profile: ThemeProfile,
    ) -> bytes:
        """Apply title and footer overlays from theme profile onto cover data.

        Convenience method that checks if overlays are configured and applies them.
        Use this instead of duplicating the check-and-compose pattern.

        Args:
            cover_data: Raw bytes of the generated cover image
            theme_profile: Theme profile with cover_title_image and cover_footer_image

        Returns:
            Cover data with overlays applied, or original data if no overlays configured
        """
        if not theme_profile.cover_title_image and not theme_profile.cover_footer_image:
            return cover_data

        return self.compose_cover(
            base_cover=cover_data,
            title_image_path=theme_profile.cover_title_image,
            footer_image_path=theme_profile.cover_footer_image,
        )

    def compose_cover(
        self,
        base_cover: bytes,
        title_image_path: str,
        footer_image_path: str,
    ) -> bytes:
        """Compose a cover by overlaying title and footer images.

        Args:
            base_cover: Raw bytes of the base cover image (generated by Flux 2)
            title_image_path: Path to title PNG (transparent background), relative to project root
            footer_image_path: Path to footer PNG (transparent background), relative to project root

        Returns:
            Composed cover image as PNG bytes
        """
        base = Image.open(io.BytesIO(base_cover)).convert("RGBA")
        cover_width, cover_height = base.size

        logger.info(f"Compositing cover: {cover_width}x{cover_height}, " f"padding={PADDING_PX}px (safe zone + bleed)")

        # Max width for overlays: cover width minus padding on each side
        max_overlay_width = cover_width - (2 * PADDING_PX)
        max_title_height = int(cover_height * TITLE_MAX_HEIGHT_RATIO)
        max_footer_height = int(cover_height * FOOTER_MAX_HEIGHT_RATIO)

        # Overlay title (top, centered)
        if self._validate_overlay_path(title_image_path):
            title_path = Path(title_image_path)
            if title_path.exists():
                title_img = Image.open(title_path).convert("RGBA")
                title_img = self._fit_dimensions(title_img, max_overlay_width, max_title_height)

                x = (cover_width - title_img.width) // 2
                y = PADDING_PX
                base.paste(title_img, (x, y), title_img)
                logger.info(f"Title overlaid at ({x}, {y}), size={title_img.size}")
            else:
                logger.warning(f"Title image not found: {title_path}, skipping overlay")

        # Overlay footer (bottom, centered)
        if self._validate_overlay_path(footer_image_path):
            footer_path = Path(footer_image_path)
            if footer_path.exists():
                footer_img = Image.open(footer_path).convert("RGBA")
                footer_img = self._fit_dimensions(footer_img, max_overlay_width, max_footer_height)

                x = (cover_width - footer_img.width) // 2
                y = cover_height - FOOTER_BOTTOM_PADDING_PX - footer_img.height
                base.paste(footer_img, (x, y), footer_img)
                logger.info(f"Footer overlaid at ({x}, {y}), size={footer_img.size}")
            else:
                logger.warning(f"Footer image not found: {footer_path}, skipping overlay")

        # Convert back to PNG bytes
        output = io.BytesIO()
        base.save(output, format="PNG")
        return output.getvalue()

    @staticmethod
    def _fit_dimensions(image: Image.Image, max_width: int, max_height: int) -> Image.Image:
        """Resize image proportionally to fit within max_width and max_height.

        Uses the most constraining dimension to maintain aspect ratio.

        Args:
            image: PIL Image to resize
            max_width: Maximum allowed width in pixels
            max_height: Maximum allowed height in pixels

        Returns:
            Resized image (or original if already fits)
        """
        if image.width <= max_width and image.height <= max_height:
            return image

        ratio = min(max_width / image.width, max_height / image.height)
        new_width = int(image.width * ratio)
        new_height = int(image.height * ratio)
        return image.resize((new_width, new_height), Image.LANCZOS)
